module.exports = {
  content: [
    "./index.html",
    "./app/**/*.{html,ts,tsx,jsx,js}",
  ],
  theme: {
    extend: {
      colors: {
        foreground: "hsl(var(--foreground))",
        "primary-foreground": "#ffffff",
        "muted-foreground": "#6b7280",
        "input-background": "#ffffff",
        input: "#e5e7eb",
        ring: "#3b82f6",
        destructive: "#ef4444",
        "outline": "#777587",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb695",
        "surface-dim": "#dcd8e5",
        "background": "#fcf8ff",
        "tertiary": "#7e3000",
        "secondary-fixed-dim": "#68dba9",
        "secondary": "#006c4a",
        "surface": "#fcf8ff",
        "on-tertiary-container": "#ffd2be",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#351000",
        "status-warning": "#f59e0b",
        "on-primary-fixed": "#0f0069",
        "surface-variant": "#e4e1ee",
        "surface-tint": "#4d44e3",
        "header-end": "#3730a3",
        "list-teal": "#0d9488",
        "on-secondary-container": "#00714e",
        "on-primary-container": "#dad7ff",
        "on-background": "#1b1b24",
        "on-error": "#ffffff",
        "list-cyan": "#0891b2",
        "header-mid": "#1d4ed8",
        "on-secondary-fixed-variant": "#005137",
        "primary-fixed": "#e2dfff",
        "on-primary": "#ffffff",
        "surface-bright": "#fcf8ff",
        "secure-void": "#020617",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed": "#002114",
        "inverse-primary": "#c3c0ff",
        "generator-pink": "#db2777",
        "generator-purple": "#9333ea",
        "inverse-on-surface": "#f3effc",
        "surface-container-highest": "#e4e1ee",
        "on-surface": "#1b1b24",
        "on-surface-variant": "#464555",
        "tertiary-container": "#a44100",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae6f4",
        "primary-container": "#4f46e5",
        "error-container": "#ffdad6",
        "surface-container-low": "#f5f2ff",
        "secondary-container": "#82f5c1",
        "surface-container": "#f0ecf9",
        "on-tertiary-fixed-variant": "#7b2f00",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary": "#ffffff",
        "header-start": "#4f46e5",
        "primary": "#3525cd",
        "tertiary-fixed": "#ffdbcc",
        "status-destructive": "#dc2626",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#302f39",
        "secondary-fixed": "#85f8c4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "card-gap": "1.25rem",
        "toolbar-height": "4rem",
        "internal-gutter": "1rem",
        "container-padding": "1.5rem"
      },
      fontFamily: {
        "section-label": ["JetBrains Mono"],
        "nav-tab": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "data-mono": ["JetBrains Mono"],
        "body-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "section-label": ["10px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "800" }],
        "nav-tab": ["14px", { "lineHeight": "20px", "fontWeight": "900" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "fontWeight": "900" }],
        "data-mono": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "22px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
